apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      volumes:
      - name: ssl-certs
        secret:
          secretName: nginx-ssl-secret # Name of the TLS secret
      imagePullSecrets:
      - name: regcred    # Dockerhub credentials
      containers:
      - name: notes-app-container
        image: monsotal/notes-app-monolithic:<TAG> 
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        volumeMounts:
        - name: ssl-certs
          mountPath: /etc/nginx/ssl
          readOnly: true
