apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      volumes: []
      imagePullSecrets:
      - name: regcred
      containers:
      - name: notes-app-container
        image: monsotal/notes-app-monolithic:0.0.1
        ports:
        - containerPort: 80
        env:
        - name: PROJECTDIR
          value: "/home/Notes-app-monolithic"
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: notes-app-config
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: notes-app-config
              key: JWT_SECRET
