apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
spec:
  selector:
    app: notes-app
  type: NodePort
  ports:
  - name: https
    port: 443          # Expose HTTPS traffic
    targetPort: 443    # Map to Nginx's HTTPS listener
    nodePort: 30443    # NodePort for HTTPS
    protocol: TCP
